### ISSUE TITLE
Goto in a new split

### ISSUE THREAD

**Issue by tvatter** [ncm2/ncm2-pyclang#23]
Hi and thanks for ncm2-pyclang, it works like a charm :)

Apologies for writing here, as it's definitely not an issue, but I'm still new to neovim and I'm not sure where to ask this.

I'm using the following line for the goto command:

`autocmd FileType c,cpp nnoremap <buffer> gd :<c-u>call ncm2_pyclang#goto_declaration()<cr>`

It works fine, but it opens the file in the split from where the command was called. Is there any way to have the goto automatically open a new split or something similar?

**Comment by roxma** [comment]
Hi, I'm too busy to add this feature. PR is welcome.

**Comment by tvatter** [comment]
I just did, sorry for the delay, I was super busy (and admittedly was too afraid to even start since I know nothing about vimscript).
