### ISSUE TITLE
Behavior when using auto

### ISSUE THREAD

**Issue by tvatter** [ncm2/ncm2-pyclang#24]
Let's assume that I have the following:

```
auto obj1 = MyClass;
MyClass obj2;
```

Then, when typing `obj1.`, a popup menu appears with the methods of `MyClass`, but not when typing `obj2.`.

Is it intended? Is there something that I can/should do to get the popup menu for objects declared using the `auto` keyword?

**Comment by roxma** [comment]
You should provide detailed information to reproduce the issue:

1. minimal vimrc
2. The C demo code
3. The libclang.so version, nvim version, and your system version

**Comment by tvatter** [comment]
Hi,

I didn't provide the MWE because I wasn't sure whether this is actually an issue or whether the methods of objects declared using the C++11 `auto` keyword aren't even supposed to appear in the popup menu.

Since the methods of such objects appeared when using YouCompleteMe, I guess that this is related to ncm2 and ncm2-pyclang, but again, I am not sure whether this is an issue or actually the intended behavior.

I will produce an MWE on Monday.

**Comment by tvatter** [comment]
Yeah, I was just trying to produce this MWE when I noticed that the behavior was not appearing anymore. Not sure what changed, but glad that it works. Sorry.
